### ISSUE TITLE
No branches or pull requests

### ISSUE THREAD

**Issue by tokyodaito** [Kantemir000/Art#1]
Как решить данную проблему ? Дается 30 секунд.

**Comment by KantemirK** [comment]
Поверх этого проекта будет интерактивная часть, чтобы на JS потренить. Дизайн и вёрстка не моё, такую какашку я бы не сделал.

**Comment by tokyodaito** [comment]
Бро, я случайно. Норм проект. Я просто рандомные слова вбил. Без негатива
